export const ADD_PERSONS = 'ADD_PERSONS';
export const SORT_PERSONS = 'SORT_PERSONS';
export const ADD_CURRENT_PERSON = 'ADD_CURRENT_PERSON';
export const UPDATE_CURRENT_PERSON = 'UPDATE_CURRENT_PERSON';
export const ADD_CURRENT_PERSON_RELATIVES = 'ADD_CURRENT_PERSON_RELATIVES';
export const SORT_RELATIVES = 'SORT_RELATIVES';